use_frameworks!

platform :ios, '9.0'

target 'CafeCommunitySDK_Example' do
  pod 'CafeCommunitySDK', :path => '../'

  target 'CafeCommunitySDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
